default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: postgres
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pipeline_hq_development

test:
  <<: *default
  database: pipeline_hq_test

production:
  primary: &primary_production
    <<: *default
    database: pipeline_hq_production
    username: pipeline_hq
    password: <%= ENV["PIPELINE_HQ_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: pipeline_hq_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: pipeline_hq_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: pipeline_hq_production_cable
    migrations_paths: db/cable_migrate
