service: pipeline_hq

image: wasdevv/pipeline_hq

servers:
  web:
    - <ORACLE_VM_PUBLIC_IP>

proxy:
  ssl: true
  host: <YOUR_DOMAIN>
  app_port: 3000

registry:
  server: ghcr.io
  username: wasdevv
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
    - ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY
    - ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY
    - ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT
  clear:
    SOLID_QUEUE_IN_PUMA: true
    DB_HOST: pipeline_hq-postgres
    DB_NAME: pipeline_hq_production
    DB_USERNAME: pipeline_hq
    WEB_CONCURRENCY: 2
    RAILS_MAX_THREADS: 5

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"
  migrate: app exec "bin/rails db:migrate"
  seed: app exec "bin/rails db:seed"

volumes:
  - "pipeline_hq_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: arm64

accessories:
  postgres:
    image: postgres:16-alpine
    host: <ORACLE_VM_PUBLIC_IP>
    port: "127.0.0.1:5432:5432"
    env:
      clear:
        POSTGRES_USER: pipeline_hq
        POSTGRES_DB: pipeline_hq_production
      secret:
        - POSTGRES_PASSWORD
    files:
      - config/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    directories:
      - data:/var/lib/postgresql/data
